export const SET_ENTRY_STREAM_UNSUBSCRIBER = 'SET_ENTRY_STREAM_UNSUBSCRIBER';
export const ADD_ENTRY = 'ADD_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';