export const SET_ACCOUNT_STREAM_UNSUBSCRIBER = 'SET_ACCOUNT_STREAM_UNSUBSCRIBER';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';